# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cino2YXVYG5XhNIvg7S8zm_horX_j-x_
"""

import warnings
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics.pairwise import cosine_similarity
from xgboost import XGBClassifier
import seaborn as sns
import matplotlib.pyplot as plt
from imblearn.over_sampling import SMOTE
import joblib

# Suppress warnings
warnings.filterwarnings('ignore')

# Load the dataset
data = pd.read_csv('/content/sample_5000.csv')

# Remove duplicates
print(f"Original dataset size: {len(data)}")
data = data.drop_duplicates()
print(f"Dataset size after removing duplicates: {len(data)}")

# Select features
features = ['Gender', 'Age', 'BMI', 'Smoker', 'HeartDiseaseorAttack', 'PhysActivity', 'PhysHlth', 'DiffWalk', 'AnyHealthcare', 'BMI_Category', 'AgeGroup']
X = data[features]

# Create a dictionary for workout descriptions
workout_desc = data[['Workout1', 'Desc1', 'Workout2', 'Desc2', 'Workout3', 'Desc3']].copy()
workout_desc = workout_desc.fillna('No description available')

# Handle missing values in X
X = X.copy()
for col in X.select_dtypes(include=['float64', 'int64']).columns:
    X[col] = X[col].fillna(X[col].mean())
for col in X.select_dtypes(include=['object']).columns:
    X[col] = X[col].fillna(X[col].mode()[0])

# Encode categorical features and save LabelEncoders
le_dict = {}
X_encoded = X.copy()
for col in X.select_dtypes(include=['object']).columns:
    le_dict[col] = LabelEncoder()
    X_encoded[col] = le_dict[col].fit_transform(X[col])

# Scale numerical features for similarity calculations
numerical_cols = ['Age', 'BMI', 'PhysHlth']
scaler = StandardScaler()
X_scaled = X_encoded.copy()
X_scaled[numerical_cols] = scaler.fit_transform(X_encoded[numerical_cols])

# Filter rare classes for data, X, and workout_desc simultaneously
min_samples = 10
initial_size = len(data)
for workout in ['Workout1', 'Workout2', 'Workout3']:
    value_counts = data[workout].value_counts()
    valid_classes = value_counts[value_counts >= min_samples].index
    data = data[data[workout].isin(valid_classes)]
    X_encoded = X_encoded.loc[data.index]
    X_scaled = X_scaled.loc[data.index]
    workout_desc = workout_desc.loc[data.index]

# Reindex all dataframes
data = data.reset_index(drop=True)
X_encoded = X_encoded.reset_index(drop=True)
X_scaled = X_scaled.reset_index(drop=True)
workout_desc = workout_desc.reset_index(drop=True)
print(f"Dataset size after removing rare classes: {len(data)}")
print(f"Rare classes removed: {initial_size - len(data)} rows")

# Verify index alignment
assert X_encoded.index.equals(data.index), "X_encoded and data indices do not match"
assert X_scaled.index.equals(data.index), "X_scaled and data indices do not match"
assert workout_desc.index.equals(data.index), "workout_desc and data indices do not match"

# Train models with SMOTE
models = {}
accuracies = {}
feature_importances = {}
confusion_matrices = {}
label_encoders = {}

for workout in ['Workout1', 'Workout2', 'Workout3']:
    y = data[workout]
    label_encoders[workout] = LabelEncoder()
    y_encoded = label_encoders[workout].fit_transform(y)

    # Apply SMOTE with adjusted k_neighbors for smaller classes
    smote = SMOTE(random_state=42, k_neighbors=3)
    X_resampled, y_resampled = smote.fit_resample(X_encoded, y_encoded)

    value_counts = pd.Series(y_resampled).value_counts()
    total_samples = len(y_resampled)
    class_weights = {i: total_samples / (len(value_counts) * count) for i, count in enumerate(value_counts)}
    sample_weights = np.array([class_weights[yi] for yi in y_resampled])

    X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)
    sample_weights_train = sample_weights[X_train.index]

    # Train model with class weights
    model = XGBClassifier(n_estimators=100, max_depth=5, random_state=42, eval_metric='mlogloss',
                          reg_lambda=1.0, reg_alpha=0.5, scale_pos_weight=class_weights)
    model.fit(X_train, y_train, sample_weight=sample_weights_train)

    cv_scores = cross_val_score(model, X_resampled, y_resampled, cv=5, scoring='accuracy')
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)

    models[workout] = model
    accuracies[workout] = {'test_accuracy': accuracy, 'cv_accuracy': np.mean(cv_scores)}
    feature_importances[workout] = model.feature_importances_
    confusion_matrices[workout] = cm

# Save models, scaler, and label encoders
joblib.dump(scaler, 'scaler.joblib')
for col in le_dict:
    joblib.dump(le_dict[col], f'label_encoder_{col}.joblib')
for workout in ['Workout1', 'Workout2', 'Workout3']:
    joblib.dump(models[workout], f'xgb_model_{workout}.joblib')
    joblib.dump(label_encoders[workout], f'label_encoder_{workout}.joblib')
print("Models, scaler, and label encoders saved successfully.")

# Display Confusion Matrix as heatmap
for workout in ['Workout1', 'Workout2', 'Workout3']:
    plt.figure(figsize=(10, 8))
    sns.heatmap(confusion_matrices[workout], annot=True, fmt='d', cmap='Blues')
    plt.title(f'Confusion Matrix for {workout}')
    plt.xlabel('Predicted')
    plt.ylabel('True')
    plt.show()

# Function to recommend workouts based on similarity
def recommend_workouts_similarity(new_user_df, X_scaled, data, workout_desc, top_n=1):
    # Check for exact match
    matched = data[
        (data['Gender'] == new_user_df['Gender'].iloc[0]) &
        (data['Age'] == new_user_df['Age'].iloc[0]) &
        (data['BMI'] == new_user_df['BMI'].iloc[0]) &
        (data['Smoker'] == new_user_df['Smoker'].iloc[0]) &
        (data['HeartDiseaseorAttack'] == new_user_df['HeartDiseaseorAttack'].iloc[0]) &
        (data['PhysActivity'] == new_user_df['PhysActivity'].iloc[0]) &
        (data['PhysHlth'] == new_user_df['PhysHlth'].iloc[0]) &
        (data['DiffWalk'] == new_user_df['DiffWalk'].iloc[0]) &
        (data['AnyHealthcare'] == new_user_df['AnyHealthcare'].iloc[0])
    ]

    if not matched.empty:
        return matched[['Workout1', 'Desc1', 'Workout2', 'Desc2', 'Workout3', 'Desc3'] + features].head(top_n)

    # Flexible filtering with relaxed ranges
    filtered_data = data[
        (data['BMI'].between(new_user_df['BMI'].iloc[0] - 7, new_user_df['BMI'].iloc[0] + 7)) &
        (data['Age'].between(new_user_df['Age'].iloc[0] - 10, new_user_df['Age'].iloc[0] + 10)) &
        (data['PhysHlth'].between(new_user_df['PhysHlth'].iloc[0] - 5, new_user_df['PhysHlth'].iloc[0] + 5))
    ].copy()

    if filtered_data.empty:
        print("No similar profiles found in the dataset.")
        return pd.DataFrame()

    filtered_data = filtered_data.reset_index(drop=True)
    workout_desc_filtered = workout_desc.loc[filtered_data.index].reset_index(drop=True)

    # Encode and scale filtered data
    X_filtered = filtered_data[features].copy()
    for col in ['BMI_Category', 'AgeGroup']:
        X_filtered[col] = le_dict[col].transform(X_filtered[col])
    X_filtered[numerical_cols] = scaler.transform(X_filtered[numerical_cols])

    # Scale user input
    user_df_encoded = new_user_df.copy()
    for col in ['BMI_Category', 'AgeGroup']:
        user_df_encoded[col] = le_dict[col].transform(user_df_encoded[col])
    user_df_scaled = user_df_encoded.copy()
    user_df_scaled[numerical_cols] = scaler.transform(user_df_encoded[numerical_cols])

    # Compute cosine similarity
    weights = np.array([2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0])  # Emphasize ActualAge, BMI, PhysHlth
    X_filtered_scaled = X_filtered * weights
    X_user_scaled = user_df_scaled * weights
    cosine_sim = cosine_similarity(X_user_scaled, X_filtered_scaled)
    cosine_sim_normalized = (cosine_sim + 1) / 2
    sim_scores = list(enumerate(cosine_sim_normalized[0]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[:top_n]
    sim_indices = [i[0] for i in sim_scores]

    print("\nIndividual similarity scores for recommended workouts:")
    for idx, score in sim_scores:
        print(f"Profile {idx}: {score * 100:.2f}%")

    return_cols = ['Workout1', 'Desc1', 'Workout2', 'Desc2', 'Workout3', 'Desc3'] + features
    return filtered_data.iloc[sim_indices][return_cols]

# Function to predict workouts
def predict_user_workouts():
    confidence_threshold = 0.90  # Confidence threshold set to 90%
    while True:
        print("\n=== Workout Recommendation System ===")
        print("Enter your details to get personalized workout recommendations.")

        try:
            user_data = {}
            user_data['Gender'] = int(input("Enter your gender (0 for Female, 1 for Male): "))
            if user_data['Gender'] not in [0, 1]:
                print("Error: Gender must be 0 or 1.")
                continue

            user_data['Age'] = int(input("Enter your age (18-100): "))
            if not 18 <= user_data['Age'] <= 100:
                print("Error: Age must be between 18 and 100.")
                continue

            user_data['BMI'] = float(input("Enter your BMI (15-50): "))
            if not 15 <= user_data['BMI'] <= 50:
                print("Error: BMI must be between 15 and 50.")
                continue

            user_data['Smoker'] = int(input("Are you a smoker? (0 for No, 1 for Yes): "))
            if user_data['Smoker'] not in [0, 1]:
                print("Error: Smoker must be 0 or 1.")
                continue

            user_data['HeartDiseaseorAttack'] = int(input("Do you have heart disease or attack history? (0 for No, 1 for Yes): "))
            if user_data['HeartDiseaseorAttack'] not in [0, 1]:
                print("Error: HeartDiseaseorAttack must be 0 or 1.")
                continue

            user_data['PhysActivity'] = int(input("Are you physically active? (0 for No, 1 for Yes): "))
            if user_data['PhysActivity'] not in [0, 1]:
                print("Error: PhysActivity must be 0 or 1.")
                continue

            user_data['PhysHlth'] = int(input("Enter number of days with poor physical health in last 30 days (0-30): "))
            if not 0 <= user_data['PhysHlth'] <= 30:
                print("Error: Physical health days must be between 0 and 30.")
                continue

            user_data['DiffWalk'] = int(input("Do you have difficulty walking? (0 for No, 1 for Yes): "))
            if user_data['DiffWalk'] not in [0, 1]:
                print("Error: DiffWalk must be 0 or 1.")
                continue

            user_data['AnyHealthcare'] = int(input("Do you have any healthcare? (0 for No, 1 for Yes): "))
            if user_data['AnyHealthcare'] not in [0, 1]:
                print("Error: AnyHealthcare must be 0 or 1.")
                continue

            # Automatically calculate BMI_Category
            if user_data['BMI'] < 18.5:
                user_data['BMI_Category'] = 'Underweight'
            elif 18.5 <= user_data['BMI'] < 25:
                user_data['BMI_Category'] = 'Normal'
            elif 25 <= user_data['BMI'] < 30:
                user_data['BMI_Category'] = 'Overweight'
            else:
                user_data['BMI_Category'] = 'Obese'

            # Automatically calculate AgeGroup
            if 18 <= user_data['Age'] <= 35:
                user_data['AgeGroup'] = 'Young'
            elif 35 < user_data['Age'] <= 60:
                user_data['AgeGroup'] = 'Middle-aged'
            else:
                user_data['AgeGroup'] = 'Senior'

            # Create DataFrame for user input
            user_df = pd.DataFrame([user_data])

            # Encode categorical features
            user_df_encoded = user_df.copy()
            for col in ['BMI_Category', 'AgeGroup']:
                if col in le_dict:
                    try:
                        user_df_encoded[col] = le_dict[col].transform(user_df[col])
                    except ValueError:
                        print(f"Error: Invalid {col} calculated. Using default: {user_data[col]}")
                        user_df_encoded[col] = le_dict[col].transform([user_data[col]])[0]

            # Fetch similarity-based recommendations for potential use
            recommended_workouts = recommend_workouts_similarity(user_df, X_scaled, data, workout_desc, top_n=1)
            sim_based_recommendations = {}
            if not recommended_workouts.empty:
                for workout in ['Workout1', 'Workout2', 'Workout3']:
                    sim_based_recommendations[workout] = recommended_workouts[workout].iloc[0]
                    sim_based_recommendations[f'Desc{workout[-1]}'] = recommended_workouts[f'Desc{workout[-1]}'].iloc[0]

            # Predict workouts using XGBoost models (for reference)
            print("\nModel-Based Workout Recommendations (for reference):")
            user_predictions = {}
            confidences = {}
            for workout in ['Workout1', 'Workout2', 'Workout3']:
                pred_encoded = models[workout].predict(user_df_encoded)[0]
                pred_workout = label_encoders[workout].inverse_transform([pred_encoded])[0]
                pred_proba = models[workout].predict_proba(user_df_encoded)[0]
                confidence = max(pred_proba)

                # If confidence is below 90% and similarity-based recommendations are available, use them
                if confidence < confidence_threshold and not recommended_workouts.empty:
                    user_predictions[workout] = sim_based_recommendations[workout]
                    desc_col = f'Desc{workout[-1]}'
                    desc = sim_based_recommendations[desc_col]
                    confidences[workout] = 0.90  # Default confidence for similarity-based
                    print(f"{workout}: {user_predictions[workout]} (Confidence: {confidences[workout]:.2f} - Replaced with similarity-based recommendation)")
                    print(f"{desc_col}: {desc}\n")
                else:
                    user_predictions[workout] = pred_workout
                    confidences[workout] = confidence
                    desc_col = f'Desc{workout[-1]}'
                    desc = workout_desc.loc[workout_desc[workout] == pred_workout, desc_col].iloc[0] if not workout_desc[workout_desc[workout] == pred_workout].empty else "No description available"
                    print(f"{workout}: {pred_workout} (Confidence: {confidences[workout]:.2f})")
                    print(f"{desc_col}: {desc}\n")

            # Final recommendations based on closest profile
            print("\nFinal Workout Recommendations (based on closest profile):")
            if not recommended_workouts.empty:
                print(recommended_workouts[['Workout1', 'Desc1', 'Workout2', 'Desc2', 'Workout3', 'Desc3']])
                # Calculate efficiency score
                user_df_scaled = user_df_encoded.copy()
                user_df_scaled[numerical_cols] = scaler.transform(user_df_encoded[numerical_cols])
                X_recommended = recommended_workouts[features].copy()
                for col in ['BMI_Category', 'AgeGroup']:
                    X_recommended[col] = le_dict[col].transform(X_recommended[col])
                X_recommended[numerical_cols] = scaler.transform(X_recommended[numerical_cols])
                weights = np.array([2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0])
                similarities = cosine_similarity(user_df_scaled * weights, X_recommended * weights)[0]
                similarities_normalized = (similarities + 1) / 2
                efficiency_score = np.mean(similarities_normalized) * 100
                print(f"\nEfficiency score for final recommendations: {efficiency_score:.2f}%")
            else:
                print("No similar workout recommendations available.")

            # Display model accuracy as reference
            print("\nModel Test Accuracies (for reference):")
            for workout in ['Workout1', 'Workout2', 'Workout3']:
                print(f"{workout}: {accuracies[workout]['test_accuracy']:.2f}")

            # Ask if user wants to try again
            retry = input("\nDo you want to enter another set of data? (yes/no): ").lower()
            if retry != 'yes':
                break

        except ValueError as e:
            print(f"Error: Invalid input. Please enter valid numbers for numerical fields. Details: {e}")
        except Exception as e:
            print(f"Error: Something went wrong. Details: {e}")

# Run the prediction function
if __name__ == "__main__":
    predict_user_workouts()